#!/bin/sh

export version=r14

# To save writting a config file parser, we just use
# the shell to set environment variables that we
# can read.
. /etc/ubootchart/ubootchart.conf

####################################################
# Now start capturing the stats:
####################################################
/sbin/ubootchartd_bin &
exec $init_prog

